export const SIGNUP_SUCCESS = 'VAXITRACK/AUTH/SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'VAXITRACK/AUTH/SIGNUP_FAIL';
export const LOGIN_SUCCESS = 'VAXITRACK/AUTH/LOGIN_SUCCESS';
export const LOGIN_FAIL = 'VAXITRACK/AUTH/LOGIN_FAIL';
export const LOGOUT = 'VAXITRACK/AUTH/LOGOUT';
