export const SIGNUP_SUCCESS = 'VAXITRACK/SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'VAXITRACK/SIGNUP_FAIL';
export const LOGIN_SUCCESS = 'VAXITRACK/LOGIN_SUCCESS';
export const LOGIN_FAIL = 'VAXITRACK/LOGIN_FAIL';
export const LOGOUT = 'VAXITRACK/LOGOUT_SUCCESS';
