export const GET_ALL_CHILDREN = 'VAXITRACK/CHILDREN/GET_ALL_CHILDREN'
export const SET_VACCINE_LIST = 'VAXITRACK/CHILDREN/SET_VACCINE_LIST'
export const SET_SELECTED_CHILD = 'VAXITRACK/CHILDREN/SET_SELECTED_CHILD'
export const ADD_NEW_CHILD = 'VAXITRACK/CHILDREN/ADD_NEW_CHILD'
export const UPDATE_CHILD_INFO = 'VAXITRACK/CHILDREN/UPDATE_CHILD_INFO'
export const DELETE_CHILD_RECORD = 'VAXITRACK/CHILDREN/DELETE_CHILD_RECORD'

